Fix utf8 stash path
storm-devs/storm-engine pull request #237
Opened 2021-10-18 19:53 UTC by mitrokosta

``const std::string toUtf8(u8str.begin(), u8str.end());`` mangles cyrillic characters in paths, results in crashes

2021-10-18 20:33 UTC, espkk requested changes

2021-10-18 20:33 UTC, espkk commented on src/libs/util/include/storm/fs.h
> -        const std::string toUtf8(u8str.begin(), u8str.end());
Indeed, UTF-8 support still seems to be unstable. But we need to check everything very carefully to avoid introducing new issues.

I do not understand the point of `toUtf8`, it seems that `u8string` should be enough.
But anyway, this code does not "mangle" characters. The codepoint of Cyrillic char consists of two bytes, and therefore byte-array view becomes meaningless as Visual Studio only recognises ANSI/wchar_t.
It should be still a valid path in UTF-8.

Eventually, we want to achieve a transition to UTF-8 avoiding wchar_t. But if it helps to solve issues we can leave it that way.
But then we need to make sure that every part of code that indirectly gets this function's value expects wchar_t.

Briefly, I can remember `sentry-native` likely indeed expects native encoding. But we have to check and test(debug) that and all other places. I think there are only a few

2021-10-19 15:45 UTC, np-c0mp1ete commented on src/libs/util/include/storm/fs.h
> -        const std::string toUtf8(u8str.begin(), u8str.end());
on a side note, to properly view utf8 strings in VS you need to add `s8` like explained [here](https://docs.microsoft.com/en-us/visualstudio/debugger/format-specifiers-in-cpp?view=vs-2019#BKMK_Visual_Studio_2012_format_specifiers). maybe that helps

2021-10-19 16:15 UTC, espkk approved these changes
Aight, everything seems to be working with the native encoding.
Thanks for the PR!

2021-10-19 16:15 UTC, merged