Procedural head look
storm-devs/storm-engine pull request #278
Opened 2021-12-12 06:44 UTC by 345frosty

2021-12-12 07:36 UTC, Artess999 commented
Have you checked on other skeletons than “man”? I'm not sure that neck idx is always 16

2021-12-12 16:05 UTC, 345frosty commented
> Have you checked on other skeletons except man.an? I'm not sure that neck bone idx is always 16 Maybe it could be moved to scripts and if it is not set from scripts it'll be 16?

I've added an option in .ani file. Now you can change default head bone index by
`data = "Head bone index", "16"`

2021-12-12 17:31 UTC, Artess999 commented
> > Have you checked on other skeletons except man.an? I'm not sure that neck bone idx is always 16 Maybe it could be moved to scripts and if it is not set from scripts it'll be 16?
> 
> I've added an option in .ani file. Now you can change head bone index by `data = "Head bone index", "16"`

Thanks!

2021-12-12 22:19 UTC, espkk requested changes
Thanks for the PR again 👍 
Please check the additional comments and I think it is to be merged right after.

2021-12-12 22:19 UTC, espkk commented on src/libs/location/src/Character.cpp
> +        case headlook_character:
This is evil and normally we want to get rid of such code: instead, additional `if` or lambda for shared code should've been used. 
But it is FYI, I do not insist on rewriting this part.

2021-12-12 22:19 UTC, espkk commented on src/libs/location/src/Character.cpp
> +                {
nullptr means the entity was deleted. It would make sense to change `curHeadLookState` to `headlook_default` and break

2021-12-12 22:19 UTC, espkk commented on src/libs/location/src/Character.h
> +    enum HeadLookState
Could you use `enum class` instead, please? There is a lot of nasty legacy things, but for the new code, we prefer to avoid bad practices.

2021-12-19 07:56 UTC, 345frosty commented
Thank you @espkk

2021-12-19 13:37 UTC, espkk approved these changes
thanks, all's good now! 👍

2021-12-19 13:37 UTC, merged