Fix comparing strings with raw string literals and count parameter
storm-devs/storm-engine pull request #285
Opened 2021-12-30 08:30 UTC by Hammie

Fixes case-insensitive comparisons for raw string literals: `const char*` and `const char[]`.

Also adds an option to only compare `count` number of characters, for partial string comparisons.

2021-12-30 18:16 UTC, q4a commented
Sorry for delay. I found error, but don't understand where it was. This example returns true, but should be false:
`std::cout << "comp08=0: " << iEquals(".txt1", ".txt2", 5) << "\n";`
I think that better to write:
```
template <typename Range1T, typename Range2T = Range1T>
bool iEquals(const Range1T &first, const Range2T &second, const size_t count)
{
    detail::is_iequal comp;

    const auto first_begin = std::begin(first);
    const auto second_begin = std::begin(second);

    const auto first_end = std::end(first);
    const auto second_end = std::end(second);

    const auto first_length = std::distance(first_begin, first_end);
    const auto second_length = std::distance(second_begin, second_end);
    if (first_length < count || second_length < count)
    {
        if (first_length != second_length)
        {
            return false;
        }
        else
        {
            return std::equal(first_begin, first_end, second_begin, second_end, comp);
        }
    }
    else
    {
        return std::equal(first_begin, first_begin + count, second_begin, second_begin + count, comp);
    }
}
```

2021-12-30 18:47 UTC, q4a requested changes

2021-12-30 18:47 UTC, q4a commented on src/libs/util/include/storm/string_compare.hpp
> +    const auto second_length = std::distance(first_begin, first_end) - 1;
here is mistake

2021-12-30 18:53 UTC, Hammie commented on src/libs/util/include/storm/string_compare.hpp
> +    const auto second_length = std::distance(first_begin, first_end) - 1;
I think I fixed it for real this time

2021-12-30 19:18 UTC, q4a approved these changes
Looks good, thank you!

2021-12-31 13:58 UTC, espkk approved these changes

2021-12-31 13:59 UTC, merged