Fixed perspective on ultrawide screens
storm-devs/storm-engine pull request #492
Opened 2023-05-05 20:49 UTC by Reksotiv

In the **SetPerspective** function, the variable **perspective** is the horizontal fov, which is set to the same value for all diagonals, and as the screen width increases, the image gets closer. For example, the horizontal fov is 90 and with an aspect ratio of 16:9 vertical fov = 59, and with an aspect ratio of 21:9 vertical fov = 47. https://themetalmuncher.github.io/fov-calc/
The perspective can be increased using the **fov_multiplier** variable in the **engine.ini** file, but after that the image looks distorted. Look at the screenshot with the barrel, without changes it is not round but oval.
Instead of manually calculating perspective projection matrix, i used this function https://learn.microsoft.com/en-us/windows/win32/direct3d9/d3dxmatrixperspectivefovlh

**Without fix fov_multiplier = 1.0**
![default-1 0](https://user-images.githubusercontent.com/29454172/236563527-b753a6ca-0132-46f8-ad81-42f6b2eaf492.jpg)
**With fix fov_multiplier = 1.0**
![moded-1 0](https://user-images.githubusercontent.com/29454172/236563584-c2797fc6-1e6c-4fb6-9f28-3ac0c334fc8b.jpg)

**Without fix fov_multiplier = 1.5**
![default2-1 5](https://user-images.githubusercontent.com/29454172/236564992-dc149df5-f7aa-4165-a3c3-166c186ba989.jpg)
**With fix fov_multiplier = 1.5**
![moded2-1 5](https://user-images.githubusercontent.com/29454172/236565018-f75e35b4-b7d2-40ba-a6c7-c7f29bda7558.jpg)

**Without fix fov_multiplier = 1.5**
![default-1 5-circle](https://user-images.githubusercontent.com/29454172/236563700-98341def-3b8b-4ddd-8ae3-681d9aece5f6.jpg)
**With fix fov_multiplier = 1.5**
![moded-1 5-circle](https://user-images.githubusercontent.com/29454172/236563725-4524a643-8bb9-4aed-bfa8-41bfa5ba64ae.jpg)

2023-05-06 07:35 UTC, Hammie commented
I think I understand the issue, and `const float fov_vert = 2.0f * atanf(tanf(perspective * 0.5f * FovMultiplier) / fAspectRatio);` is the actual part of the fix we need.

Let me double check the math.

2023-05-06 07:56 UTC, Hammie requested changes
The vertical fov calculation is indeed incorrect. This could should fix it:

``` 
perspective *= FovMultiplier;

const float near_plane = fNearClipPlane; // Distance to near clipping
const float far_plane = fFarClipPlane;   // Distance to far clipping
const float fov_horiz = perspective;     // Horizontal field of view  angle, in radians
if (fAspectRatio < 0)
{
    fAspectRatio = static_cast<float>(screen_size.y) / screen_size.x;
}
aspectRatio = fAspectRatio;
const float fov_vert = 2.f * atanf(tanf(perspective / 2.f) * fAspectRatio); // Vertical field of view  angle, in radians

const float w = 1.0f / tanf(fov_horiz * 0.5f);
const float h = 1.0f / tanf(fov_vert * 0.5f);
const float Q = far_plane / (far_plane - near_plane);

D3DMATRIX mtx{};

mtx._11 = w;
mtx._22 = h;
mtx._33 = Q;
mtx._43 = -Q * near_plane;
mtx._34 = 1.0f;
```

Only the `fov_vert` calculation needs updating

2023-05-06 08:34 UTC, Reksotiv commented
You are right, only fov_vert
![2](https://user-images.githubusercontent.com/29454172/236613124-ab7243c0-93ec-4595-bbfd-18a26bfc7b41.jpg)

2023-05-06 09:37 UTC, Hammie approved these changes, later dismissed

2023-05-06 11:20 UTC, Reksotiv commented
No, changing only fov_vert is not enough, sea camera not working properly. I made this change 3 months ago and forgot why i changed D3DMATRIX math.
**Only fov_vert**
![1](https://user-images.githubusercontent.com/29454172/236620819-781a5298-0ab5-4fb5-8fe4-9cc8511a3142.jpg)

2023-05-06 19:10 UTC, Hammie commented
What game/mod are you playing? I'm not seeing any issues when I set TEHO to a 21:9  aspect ratio.

2023-05-06 22:45 UTC, Reksotiv commented
increase **fov_multiplier** in **engine.ini**, i use 1.35 for 3440x1440 resolution. Any game, screenshots above from beyond new horizons, but all tests were in a ship pack 2.3.0a. With the change played 50 hours without problems and 10 hours in TEHO.
Without using the **D3DXMatrixPerspectiveFovLH** function, i remember changing something in the files deck_camera.cpp, free_camera.cpp, ship_camera.cpp. But why don't you want to use it? I don't know something or?

2023-05-07 08:41 UTC, Hammie commented
> But why don't you want to use it? I don't know something or?

We are trying to depend less on DirectX, for cross-platform compatibility. Adding new dependencies is something I would really like to avoid.

2023-05-07 09:43 UTC, Reksotiv commented
I understand why the problem with the camera in the sea. 
![image](https://user-images.githubusercontent.com/29454172/236669822-5049bf3f-5f08-4f62-ab9b-76f8b6a98cad.png)
in my fix i removed that and applied the FovMultiplier without changing the perspective variable
![image](https://user-images.githubusercontent.com/29454172/236669886-690fc84f-3268-4879-b7eb-60d421f3e87a.png)
and when we move from land to sea, we get a double FovMultiplier
[ship_camera.cpp](https://github.com/Reksotiv/storm-engine/blob/develop/src/libs/sea_cameras/src/ship_camera.cpp#L41)

2023-05-07 09:58 UTC, espkk commented
> > But why don't you want to use it? I don't know something or?
> 
> We are trying to depend less on DirectX, for cross-platform compatibility. Adding new dependencies is something I would really like to avoid.

Just to clarify, that's not about DirectX itself, but rather about D3DX support lib which is not present for our Linux build, so it simply won't compile unless we implement it ourselves (should be a few lines though)

> I understand why the problem with the camera in the sea. ![image](https://user-images.githubusercontent.com/29454172/236669822-5049bf3f-5f08-4f62-ab9b-76f8b6a98cad.png) in my fix i removed that and applied the FovMultiplier without changing the perspective variable ![image](https://user-images.githubusercontent.com/29454172/236669886-690fc84f-3268-4879-b7eb-60d421f3e87a.png) and when we move from land to sea, we get a double FovMultiplier [ship_camera.cpp](https://github.com/Reksotiv/storm-engine/blob/develop/src/libs/sea_cameras/src/ship_camera.cpp#L41)

Yes indeed, IIRC it was my attempt to centralize FOV customization, but it ended up setting it through sea/camera only for compatibility. Also, it's probably still missing from the SKY entity. So `fov_multiplier` was an unfinished feature.

With `fov_multiplier=1.0` it likely won't affect anything even if we merge it as is, but since we are touching this we probably want it to be complete. And this is a non-trivial task...

2023-05-07 10:12 UTC, Reksotiv commented
this code works fine for me, without saving the changed perspective by fov_multiplier in Fov variable

    const float near_plane = fNearClipPlane; // Distance to near clipping
    const float far_plane = fFarClipPlane;   // Distance to far clipping
    const float fov_horiz = perspective;     // Horizontal field of view  angle, in radians
    if (fAspectRatio < 0)
    {
        fAspectRatio = static_cast<float>(screen_size.y) / screen_size.x;
    }
    aspectRatio = fAspectRatio;
    // Vertical field of view  angle, in radians
    const float fov_vert = 2.f * atanf(tanf(perspective * 0.5f * FovMultiplier) * fAspectRatio);

    const float w = 1.0f / tanf(fov_vert * 0.5f) * fAspectRatio;
    const float h = 1.0f / tanf(fov_vert * 0.5f);
    const float Q = far_plane / (far_plane - near_plane);

    D3DMATRIX mtx{};

    mtx._11 = w;
    mtx._22 = h;
    mtx._33 = Q;
    mtx._43 = -Q * near_plane;
    mtx._34 = 1.0f;

2023-05-07 11:02 UTC, Reksotiv commented
> Yes indeed, IIRC it was my attempt to centralize FOV customization, but it ended up setting it through sea/camera only for compatibility. Also, it's probably still missing from the SKY entity. So `fov_multiplier` was an unfinished feature.

ok i realized that with this fix we might get errors in other places.

2023-05-07 11:02 UTC, closed without merging